### ISSUE TITLE
ModuleNotFoundError: No module named 'vtkIOParallelPython'

### ISSUE THREAD

**Issue by S-kewen** [ispc-lab/PointINet#4]
hello, I'm having some problems trying to run **demo.py**.

`python demo.py --is_save IS_SAVE --visualize VISUALIZE`

I have tried to fix this problem using google, but nothing, here is my try:
https://github.com/capytaine/capytaine/issues/16

thx.

Here is error msg:
`Got keys from plugin meta data ("ibus")
QFactoryLoader::QFactoryLoader() checking directory path "/home/skewen/anaconda3/envs/pointinet/bin/platforminputcontexts" ...
loaded library "/home/skewen/anaconda3/envs/pointinet/lib/python3.6/site-packages/PyQt5/Qt5/plugins/platforminputcontexts/libibusplatforminputcontextplugin.so"
QFactoryLoader::QFactoryLoader() checking directory path "/home/skewen/anaconda3/envs/pointinet/lib/python3.6/site-packages/PyQt5/Qt5/plugins/styles" ...
QFactoryLoader::QFactoryLoader() checking directory path "/home/skewen/anaconda3/envs/pointinet/bin/styles" ...
Traceback (most recent call last):
  File "/home/skewen/anaconda3/envs/pointinet/lib/python3.6/site-packages/vtkmodules/vtkIOParallel.py", line 5, in <module>
    from .vtkIOParallelPython import *
ImportError: libjsoncpp.so.19: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "demo.py", line 7, in <module>
    import mayavi.mlab as mlab
  File "/home/skewen/anaconda3/envs/pointinet/lib/python3.6/site-packages/mayavi/mlab.py", line 16, in <module>
    from mayavi.tools.camera import view, roll, yaw, pitch, move
  File "/home/skewen/anaconda3/envs/pointinet/lib/python3.6/site-packages/mayavi/tools/camera.py", line 24, in <module>
    from .engine_manager import get_engine
  File "/home/skewen/anaconda3/envs/pointinet/lib/python3.6/site-packages/mayavi/tools/engine_manager.py", line 13, in <module>
    from mayavi.core.registry import registry
  File "/home/skewen/anaconda3/envs/pointinet/lib/python3.6/site-packages/mayavi/core/registry.py", line 16, in <module>
    from mayavi.core.metadata import Metadata, import_symbol
  File "/home/skewen/anaconda3/envs/pointinet/lib/python3.6/site-packages/mayavi/core/metadata.py", line 11, in <module>
    from mayavi.core.pipeline_info import PipelineInfo
  File "/home/skewen/anaconda3/envs/pointinet/lib/python3.6/site-packages/mayavi/core/pipeline_info.py", line 12, in <module>
    from .utils import get_tvtk_dataset_name
  File "/home/skewen/anaconda3/envs/pointinet/lib/python3.6/site-packages/mayavi/core/utils.py", line 2, in <module>
    import vtk
  File "/home/skewen/anaconda3/envs/pointinet/lib/python3.6/site-packages/vtk.py", line 32, in <module>
    all_spec.loader.exec_module(all_m)
  File "/home/skewen/anaconda3/envs/pointinet/lib/python3.6/site-packages/vtkmodules/all.py", line 83, in <module>
    from .vtkIOParallel import *
  File "/home/skewen/anaconda3/envs/pointinet/lib/python3.6/site-packages/vtkmodules/vtkIOParallel.py", line 9, in <module>
    from vtkIOParallelPython import *
ModuleNotFoundError: No module named 'vtkIOParallelPython'
QLibraryPrivate::unload succeeded on "/home/skewen/anaconda3/envs/pointinet/lib/python3.6/site-packages/PyQt5/Qt5/plugins/platforminputcontexts/libibusplatforminputcontextplugin.so" 
QLibraryPrivate::unload succeeded on "/home/skewen/anaconda3/envs/pointinet/lib/python3.6/site-packages/PyQt5/Qt5/plugins/platformthemes/libqgtk3.so" 
QLibraryPrivate::unload succeeded on "/home/skewen/anaconda3/envs/pointinet/lib/python3.6/site-packages/PyQt5/Qt5/plugins/platforms/libqxcb.so" 
QLibraryPrivate::unload succeeded on "Xcursor" (faked)
`

**Comment by S-kewen** [comment]
I solved the problem, it was a version compatibility issue.
`conda install jsoncpp=1.8.3`
